/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minor;


import com.sun.glass.events.KeyEvent;
import java.sql.*;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.security.MessageDigest;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.io.FileInputStream;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

/**
 *
 * @author Bikash
 */
public class Register extends javax.swing.JFrame {

    public Register() {
        initComponents();
        setResizable(false);
        setLocation(275,150);
        setSize(870,450);
        setTitle("Register");
    }
     public void close(){
        WindowEvent winClosingEvent =new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
      public void setIcon(){
        
        
    }
     
    
    public static String getMD5(String input) {
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] messageDigest = md.digest(input.getBytes());
            BigInteger number = new BigInteger(1, messageDigest);
            String hashtext = number.toString(16);
            // Now we need to zero pad it if you actually want the full 32 chars.
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
            return hashtext;
        }
        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rln = new javax.swing.JTextField();
        rfn = new javax.swing.JTextField();
        rpsw = new javax.swing.JPasswordField();
        rmale = new javax.swing.JRadioButton();
        rfemale = new javax.swing.JRadioButton();
        rsave = new javax.swing.JButton();
        rcancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        run = new javax.swing.JTextField();

        jPasswordField1.setText("jPasswordField1");

        jPasswordField2.setText("jPasswordField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("First name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Last name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Password");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Gender");

        rln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rlnActionPerformed(evt);
            }
        });
        rln.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rlnKeyTyped(evt);
            }
        });

        rfn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfnActionPerformed(evt);
            }
        });
        rfn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rfnKeyTyped(evt);
            }
        });

        rpsw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpswActionPerformed(evt);
            }
        });
        rpsw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rpswKeyTyped(evt);
            }
        });

        buttonGroup1.add(rmale);
        rmale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rmale.setText("Male");

        buttonGroup1.add(rfemale);
        rfemale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rfemale.setText("Female");
        rfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfemaleActionPerformed(evt);
            }
        });

        rsave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rsave.setText("SAVE");
        rsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rsaveActionPerformed(evt);
            }
        });

        rcancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rcancel.setText("CANCEL");
        rcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcancelActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Username");

        run.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                runKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(273, 273, 273))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(3, 3, 3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(14, 14, 14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(1, 1, 1)))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rmale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(rfemale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(66, 66, 66))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(rsave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(62, 62, 62)
                                .addComponent(rcancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(rpsw)
                            .addComponent(rln)
                            .addComponent(run)
                            .addComponent(rfn))))
                .addGap(91, 91, 91))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rfn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(run, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rpsw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rmale)
                    .addComponent(rfemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rsave)
                    .addComponent(rcancel))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcancelActionPerformed
        close();
        User top = new User();
        top.setTab(1);
        top.setVisible(true);
        
    }//GEN-LAST:event_rcancelActionPerformed

    private void rfnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rfnActionPerformed

    private void rlnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rlnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rlnActionPerformed

    private void rsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rsaveActionPerformed
        // TODO add your handling code here:
       Dbconnect fb = new Dbconnect();
        fb.connect();
        Connection con = fb.con;
        
     try{
        /* Connection con; //connection db with java
             Statement stmt; //insert data from java to mysql
             Class.forName("com.mysql.jdbc.Driver");//driver load
             String str=("jdbc:mysql://127.0.0.1:3306/minor");//path of db
              con=DriverManager.getConnection(str,"root","");
             stmt=con.createStatement();*/
        Statement stmt; 
        stmt=con.createStatement();
         
        String fname,lname,uname,pass,gender,passmd;
        
      
        
        fname=rfn.getText();
        lname=rln.getText();
        uname=run.getText();
        pass=rpsw.getText();
        
        MessageDigest md=MessageDigest.getInstance("MD5");
        md.update(pass.getBytes(),0,pass.length());
      
        
        if(fname.isEmpty() || lname.isEmpty() || uname.isEmpty() || pass.isEmpty()){
            
            
            JOptionPane.showMessageDialog(null, "emplty field");
        }
        
        
       
        
        
        
        else{
                
        passmd=getMD5(pass);
        //JOptionPane.showMessageDialog(null,passmd);
         if(rmale.isSelected()){
            
                 String x = "insert into `register` (`firstname`,`lastname`,`username`,`password`,`gender`) values ('"+fname+"','"+lname+"','"+uname+"','"+passmd+"','male')";
                 String sql="select username from register where username='"+uname+"'";
                 ResultSet rs = stmt.executeQuery(sql);
                 int count=0;
                 while(rs.next()){
                     count+=1;
                 }
                 if(count==1){
                   JOptionPane.showMessageDialog(null, "Username Already Exist");  
                 }
                 else{
                     stmt.executeUpdate(x);
                 JOptionPane.showMessageDialog(null, "Sucessfull");
                
                 User top = new User();
                top.setTab(1);
                 top.setVisible(true);
                 close();
                 }
                
             }
         else if(rfemale.isSelected()) {
                 String x = "insert into `register` (`firstname`,`lastname`,`username`,`password`,`gender`) values ('"+fname+"','"+lname+"','"+uname+"','"+passmd+"','female')";
                 String sql="select username from register where username='"+uname+"'";
                 ResultSet rs = stmt.executeQuery(sql);
                 int count=0;
                 while(rs.next()){
                     count+=1;
                 }
                 if(count==1){
                   JOptionPane.showMessageDialog(null, "Username Already Exist");  
                 }
                 else{
                     stmt.executeUpdate(x);
                 JOptionPane.showMessageDialog(null, "Sucessfull");
                
                 User top = new User();
                 top.setTab(1);
                 top.setVisible(true);
                 close();
                 }
             }
         else{
             JOptionPane.showMessageDialog(null, "select male/female");
         }
         
        }
        
            
         
        }          
        catch(Exception e){
             System.out.println("error "+e);
         }
     
     
        
    
        
/*      
           Dbconnect fb = new Dbconnect();
        fb.connect();
        Connection con = fb.con;
        try {
            PreparedStatement ps = con.prepareStatement("Insert into register (firstname, lastname,username,password,gender) values (?,?,?,?,?)");
            ps.setString(1,rfn.getText() );
            ps.setString(2,rln.getText());
            ps.setString(3, run.getText());
            ps.setString(4,rpsw.getText() );
            if(rmale.isSelected())
            {ps.setString(5, "Male");
            ps.executeUpdate();
            }
            else
            {ps.setString(5, "Female");
            ps.executeUpdate();
            }
            System.out.println("Added");
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Cant add");
        }
  */      
        
        
        
    }//GEN-LAST:event_rsaveActionPerformed

    private void rfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rfemaleActionPerformed

    private void rfnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rfnKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)|| (c==KeyEvent.VK_BACKSPACE)||c==KeyEvent.VK_DELETE )){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "INVALID ENTRY");
        }
    }//GEN-LAST:event_rfnKeyTyped

    private void rlnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rlnKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)|| (c==KeyEvent.VK_BACKSPACE)||c==KeyEvent.VK_DELETE )){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "INVALID ENTRY");
        }
    }//GEN-LAST:event_rlnKeyTyped

    private void runKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_runKeyTyped
        char c=evt.getKeyChar();
        if((Character.isSpace(c))){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "INVALID ENTRY");
        }
    }//GEN-LAST:event_runKeyTyped

    private void rpswKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rpswKeyTyped
        char c=evt.getKeyChar();
        if((Character.isSpace(c))){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "INVALID ENTRY");
        }
    }//GEN-LAST:event_rpswKeyTyped

    private void rpswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpswActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rpswActionPerformed

    /**
     * @param args the command line argumnts
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JButton rcancel;
    private javax.swing.JRadioButton rfemale;
    private javax.swing.JTextField rfn;
    private javax.swing.JTextField rln;
    private javax.swing.JRadioButton rmale;
    private javax.swing.JPasswordField rpsw;
    private javax.swing.JButton rsave;
    private javax.swing.JTextField run;
    // End of variables declaration//GEN-END:variables
}
