package minor;

import java.awt.*;
import java.awt.event.*;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.*;
import javax.swing.*;

/**
 *
 *
 * @author Bikash
 */



public class User extends javax.swing.JFrame {

  float max_area = 0;
    float floors;

    public void setTab(int n) {
        jTabbedPane2.setSelectedIndex(n);
    }

    int sel1, sel2;

    /**
     * Creates new form User
     */
    public User() {
        initComponents();
      
       // jTabbedPane2.setMaximumSize(new Dimension(Integer.MAX_VALUE,jTabbedPane2.getMaximumSize().height));
       // jTabbedPane2.res("<html><body><table width='120'><tr><td></tr></td></table></body></html>",jpanel2);
        jarea.setEditable(false);
        jarea.setCaretPosition(0);
        jarea.getAutoscrolls();
        
        
        
        
        setResizable(false);
        setLocation(275,150);
        setSize(870,450);
        setIcon();
       // CostSplit to = new CostSplit();
        
      //  if(!to.isActive()){
           
        //}
        
        setTitle("Construction Task Management System");
         }
    
   
   public void setIcon(){
       
      

        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("image.png")));
        Icon icon0 = new ImageIcon(getClass().getResource("info.png"));
        jTabbedPane2.setIconAt(0, icon0);
        Component com =  jTabbedPane2.getTabComponentAt(0);
        //com.get
        Icon icon1 = new ImageIcon(getClass().getResource("check.png"));
        jTabbedPane2.setIconAt(1, icon1);
        Icon icon2 = new ImageIcon(getClass().getResource("calc.png"));
        jTabbedPane2.setIconAt(2, icon2);
        Icon icon3 = new ImageIcon(getClass().getResource("location.png"));
        jTabbedPane2.setIconAt(3, icon3);
        Icon icon4 = new ImageIcon(getClass().getResource("converter.png"));
        jTabbedPane2.setIconAt(4, icon4);
        
        
        //jTabbedPane2.
      
       
        
        
        
    }

    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jarea = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lun = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        register = new javax.swing.JButton();
        lpsw = new javax.swing.JPasswordField();
        jPanel10 = new javax.swing.JPanel();
        ce_1 = new javax.swing.JLabel();
        tf_total_land_area = new javax.swing.JTextField();
        ce_2 = new javax.swing.JLabel();
        tf_max_gcover = new javax.swing.JTextField();
        ce_3 = new javax.swing.JLabel();
        cb_floors = new javax.swing.JComboBox<>();
        ce_4 = new javax.swing.JLabel();
        tf_plinth_arate = new javax.swing.JTextField();
        ce_6 = new javax.swing.JLabel();
        btn_estimate = new javax.swing.JButton();
        ce_estimate = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fromcombo = new javax.swing.JComboBox<>();
        output = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tocombo = new javax.swing.JComboBox<>();
        input = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        go = new javax.swing.JButton();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane2.setBackground(new java.awt.Color(153, 153, 153));
        jTabbedPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 153, 255), null, null));
        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jarea.setBackground(new java.awt.Color(153, 204, 255));
        jarea.setColumns(20);
        jarea.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jarea.setRows(5);
        jarea.setText("\t\t\t\tBUILDING CODES\t\t\n\t\t\n* Buildings up to 10m high have to leave a minimum of 1.5m setback from \n  the border of the land plot.\n\n* Public buildings up to 17m high have to leave a minimum setback of 3m while \n  non-public buildings have to allocate for 2m setback and the minimum \n  setback for even taller buildings is 5m\n\n* Only houses up to four storeys and having a common height can be joined \n  together.\n\n* Row housing (houses attached side-by-side) taller than three storeys and \n  making it mandatory for houses to be at least one and a half metres apart.\n\n* Roads in new settlements have to be at least 8m wide for being eligible to\n  construct buildings.\n\n* Homeowners have to leave a minimum of 3m from the centre of the road \n  connecting the house to account for possible expansion.\n\n* Residential buildings can't cover more than 70 percent of land for plots up \n  to 250 square metres and the ceiling is fixed at 60 percent for larger plots.\n\n* Another major change is that outer pillars of a building or isolated column \n  footing should be built at least 1m within the boundary of the plot.\n\n* The guideline also states that fences around a house should not be taller \n  than 1.2m but installing safety nets up to 0.6m high on top is allowed.\n\n* Soil testing and seismic analysis mandatory for constructing all \n  public buildings and private houses taller than three storeys.\n\n");
        jarea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jarea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("INFO", jPanel2);

        jPanel9.setBackground(new java.awt.Color(153, 204, 255));
        jPanel9.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Password");
        jPanel9.add(jLabel1);
        jLabel1.setBounds(52, 84, 131, 22);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Username");
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 18));
        jPanel9.add(jLabel2);
        jLabel2.setBounds(52, 43, 131, 22);

        lun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lunActionPerformed(evt);
            }
        });
        jPanel9.add(lun);
        lun.setBounds(219, 36, 240, 30);

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel9.add(login);
        login.setBounds(221, 136, 88, 23);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton2);
        jButton2.setBounds(363, 136, 96, 23);

        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel9.add(register);
        register.setBounds(285, 195, 174, 23);
        jPanel9.add(lpsw);
        lpsw.setBounds(219, 87, 240, 30);

        jTabbedPane2.addTab("JOURNAL", jPanel9);

        jPanel10.setBackground(new java.awt.Color(153, 204, 255));

        ce_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ce_1.setText("Total Land Area (in square feet)");

        tf_total_land_area.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_total_land_areaMouseClicked(evt);
            }
        });
        tf_total_land_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_total_land_areaActionPerformed(evt);
            }
        });
        tf_total_land_area.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_total_land_areaKeyPressed(evt);
            }
        });

        ce_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ce_2.setText("Maximum Plinth Area of Building (in square feet)");

        tf_max_gcover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_max_gcoverMouseClicked(evt);
            }
        });
        tf_max_gcover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_max_gcoverActionPerformed(evt);
            }
        });
        tf_max_gcover.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_max_gcoverKeyPressed(evt);
            }
        });

        ce_3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ce_3.setText("Number of Floors");

        cb_floors.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "1.5", "2", "2.5", "3", "3.5", "4" }));

        ce_4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ce_4.setText("Plinth Area Rate");

        tf_plinth_arate.setText("2400");

        btn_estimate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_estimate.setText("Estimate");
        btn_estimate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_estimateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ce_6)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(ce_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(256, 256, 256))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ce_estimate)
                                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ce_2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                        .addGroup(jPanel10Layout.createSequentialGroup()
                                            .addComponent(ce_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(147, 147, 147))))
                                .addGap(25, 25, 25))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(ce_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(63, 63, 63)))
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_total_land_area)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(cb_floors, 0, 30, Short.MAX_VALUE)
                                .addGap(39, 39, 39))
                            .addComponent(tf_max_gcover)
                            .addComponent(tf_plinth_arate))))
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(btn_estimate, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(216, 216, 216))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ce_1)
                    .addComponent(tf_total_land_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(ce_6)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ce_2)
                    .addComponent(tf_max_gcover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ce_3)
                    .addComponent(cb_floors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ce_4)
                    .addComponent(tf_plinth_arate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(ce_estimate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_estimate)
                .addGap(45, 45, 45))
        );

        jTabbedPane2.addTab("COST ESTIMATION", jPanel10);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("LOCATION", jPanel11);

        jPanel13.setBackground(new java.awt.Color(153, 204, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("TO:");

        fromcombo.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        fromcombo.setMaximumRowCount(10);
        fromcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ropani", "Anna", "Paisa", "Dam", "Squar Meter", "Squar feet" }));
        fromcombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fromcomboMouseClicked(evt);
            }
        });
        fromcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromcomboActionPerformed(evt);
            }
        });

        output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("INPUT");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("FROM:");

        tocombo.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tocombo.setMaximumRowCount(10);
        tocombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ropani", "Anna", "Paisa", "Dam", "Squar Meter", "Squar feet" }));
        tocombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tocomboActionPerformed(evt);
            }
        });

        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("OUTPUT");

        go.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        go.setText("Go");
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });

        clear.setText("Reset");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fromcombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tocombo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(go, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(37, 37, 37))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tocombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(166, 166, 166))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fromcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addComponent(go)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(clear)
                .addGap(18, 18, 18))
        );

        jTabbedPane2.addTab("CONVERTER", jPanel13);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fromcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromcomboActionPerformed

        sel1 = fromcombo.getSelectedIndex();
        // JOptionPane.showMessageDialog(null, sel1);

    }//GEN-LAST:event_fromcomboActionPerformed

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        String get;

        get = input.getText();

        if (sel1 == 0 && sel2 == 0) {
            double res;
            //String r;
            res = Double.parseDouble(get);
            output.setText("" + res);

        }
        if (sel1 == 1 && sel2 == 1) {

            double res;
            //String r;
            res = Double.parseDouble(get);
            output.setText("" + res);

        }
        if (sel1 == 2 && sel2 == 2) {

            double res;
            //String r;
            res = Double.parseDouble(get);
            output.setText("" + res);

        }
        if (sel1 == 3 && sel2 == 3) {

            double res;
            //String r;
            res = Double.parseDouble(get);
            output.setText("" + res);

        }
        if (sel1 == 4 && sel2 == 4) {

            double res;
            //String r;
            res = Double.parseDouble(get);
            output.setText("" + res);

        }
        if (sel1 == 5 && sel2 == 5) {

            double res;
            //String r;
            res = Double.parseDouble(get);
            output.setText("" + res);

        }
        /*  part of ropani */

        if (sel1 == 0 && sel2 == 1) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 16;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        if (sel1 == 0 && sel2 == 2) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 16 * 4;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        if (sel1 == 0 && sel2 == 3) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 16 * 4 * 4;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        if (sel1 == 0 && sel2 == 4) {
            Double res;
            //String r;
            res = Double.parseDouble(get) * 508.74;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        if (sel1 == 0 && sel2 == 5) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 5476;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        /* part of anna */
        if (sel1 == 1 && sel2 == 0) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 0.0625;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        if (sel1 == 1 && sel2 == 2) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 4;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        if (sel1 == 1 && sel2 == 3) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 4 * 4;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        if (sel1 == 1 && sel2 == 4) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 31.76;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        if (sel1 == 1 && sel2 == 5) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 342.25;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        /* part of paisa  */
        if (sel1 == 2 && sel2 == 0) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 0.015625;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        if (sel1 == 2 && sel2 == 1) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 0.25;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        if (sel1 == 2 && sel2 == 3) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 4;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        if (sel1 == 2 && sel2 == 4) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 7.94;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        if (sel1 == 2 && sel2 == 5) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 85.56;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        /* part of dam */
        if (sel1 == 3 && sel2 == 0) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 0.00390625;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        if (sel1 == 3 && sel2 == 1) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 0.0625;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        if (sel1 == 3 && sel2 == 2) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 0.25;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        if (sel1 == 3 && sel2 == 4) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 1.985;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        if (sel1 == 3 && sel2 == 5) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 21.39;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        /* part of squar meter  */
        if (sel1 == 4 && sel2 == 0) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 0.0019656406;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        if (sel1 == 4 && sel2 == 1) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 0.0314564328;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        if (sel1 == 4 && sel2 == 2) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 0.1259445844;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        if (sel1 == 4 && sel2 == 3) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 0.5037783375;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        if (sel1 == 4 && sel2 == 5) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 10.7758186398;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        /* part of square feet */
        if (sel1 == 5 && sel2 == 0) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 0.000182615;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        if (sel1 == 5 && sel2 == 1) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 0.0029218408;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        if (sel1 == 5 && sel2 == 2) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 0.0116877045;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        if (sel1 == 5 && sel2 == 3) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 0.0467508181;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }

        if (sel1 == 5 && sel2 == 4) {
            double res;
            //String r;
            res = Double.parseDouble(get) * 0.0929035793;
            //r=Integer.toString(res);
            //JOptionPane.showMessageDialog(null, res);
            output.setText("" + res);
        }


    }//GEN-LAST:event_goActionPerformed

    private void outputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputActionPerformed

    private void tocomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tocomboActionPerformed

        sel2 = tocombo.getSelectedIndex();
        // JOptionPane.showMessageDialog(null, sel2);
    }//GEN-LAST:event_tocomboActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        output.setText("");
        input.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed

    }//GEN-LAST:event_inputActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        lun.setText(null);
        lpsw.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        close();
        Register fm = new Register();
        fm.setVisible(true);

    }//GEN-LAST:event_registerActionPerformed

    
    public static String getMD5(String input) {
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] messageDigest = md.digest(input.getBytes());
            BigInteger number = new BigInteger(1, messageDigest);
            String hashtext = number.toString(16);
            // Now we need to zero pad it if you actually want the full 32 chars.
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
            return hashtext;
        }
        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }
    
    
    
    
    
    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

        Dbconnect fb = new Dbconnect();
        fb.connect();
        Connection con = fb.con;
        try {
            Statement stmt;
            stmt = con.createStatement();
            String user = lun.getText().trim();
            String pass = lpsw.getText().trim();
            
            String passmd=getMD5(pass);
            String sql = "select username,password from register where username='" + user + "' and password='" + passmd + "' ";
            ResultSet rs = stmt.executeQuery(sql);

            int count = 0;
            while (rs.next()) {
                count = count + 1;
            }
            if (count == 1) {
                Dbentry en = new Dbentry(lun.getText());
                en.setVisible(true);
                close();

            } else {
                JOptionPane.showMessageDialog(null, "invalid username/password");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }


    }//GEN-LAST:event_loginActionPerformed

    private void lunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lunActionPerformed

    private void fromcomboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fromcomboMouseClicked

    }//GEN-LAST:event_fromcomboMouseClicked

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
        int a = jTabbedPane2.getSelectedIndex();

        if (a == 3) {
            setVisible(false);
			Location lc = new Location();
			lc.exc(this);
        }

    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void tf_total_land_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_total_land_areaActionPerformed
       
       
        
        float tot_larea = Float.parseFloat(tf_total_land_area.getText());
        max_area = (float) (tot_larea * 0.7);
        ce_6.setText("Maximum allowed ground coverage for building :   " + max_area + "  sq. ft.");
        tf_max_gcover.requestFocusInWindow();
       
    }//GEN-LAST:event_tf_total_land_areaActionPerformed

    private void tf_max_gcoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_max_gcoverActionPerformed
       
    }//GEN-LAST:event_tf_max_gcoverActionPerformed

    private void btn_estimateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_estimateActionPerformed
       
        
            
        
        if (!(tf_plinth_arate.getText().equals("") || tf_total_land_area.getText().equals("") || tf_max_gcover.getText().equals("")) ) {
           
            if(Float.parseFloat(tf_max_gcover.getText()) <= Float.parseFloat(tf_total_land_area.getText()) * 0.7){
            int ind = cb_floors.getSelectedIndex();
            switch (ind) {
                case 0:
                    floors = 1;
                    break;
                case 1:
                    floors = (float) 1.5;
                    break;
                case 2:
                    floors = 2;
                    break;
                case 3:
                    floors = (float) 2.5;
                    break;
                case 4:
                    floors = 3;
                    break;
                case 5:
                    floors = (float) 3.5;
                    break;
                case 6:
                    floors = 4;
                    break;
            }
        
            
            float est_cost = Float.parseFloat(tf_max_gcover.getText()) * floors * Float.parseFloat(tf_plinth_arate.getText());
           // ce_estimate.setText("Estimated Cost : Rs. " + est_cost);
           CostSplit cs = new CostSplit();
           cs.setVisible(true);
          // btn_estimate.setEnabled(false);
           cs.est(est_cost);
           
           
        } else {
            JOptionPane.showMessageDialog(null,"Maximum Plinth Area exceeded" );    
        }
        }
        else{
           JOptionPane.showMessageDialog(null, "Fields are empty"); 
        }
    }//GEN-LAST:event_btn_estimateActionPerformed

    private void tf_total_land_areaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_total_land_areaKeyPressed

        
       
    
        tf_total_land_area.setFocusTraversalKeysEnabled(false);
        if (evt.getKeyCode() == KeyEvent.VK_TAB){
        float tot_larea = Float.parseFloat(tf_total_land_area.getText());
        max_area = (float) (tot_larea * 0.7);
        ce_6.setText("Maximum allowed ground coverage for building :   " + max_area + "  sq. ft.");
        tf_max_gcover.requestFocusInWindow();
       
        }
        
            
        
    }//GEN-LAST:event_tf_total_land_areaKeyPressed

    private void tf_total_land_areaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_total_land_areaMouseClicked
        
    }//GEN-LAST:event_tf_total_land_areaMouseClicked

    private void tf_max_gcoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_max_gcoverMouseClicked
     // JOptionPane.showMessageDialog(null, "Please enter the plinth area");
        if(!tf_total_land_area.getText().equals("")){
       if (evt.getID()== MouseEvent.MOUSE_CLICKED) {
        float tot_larea = Float.parseFloat(tf_total_land_area.getText());
        max_area = (float) (tot_larea * 0.7);
        ce_6.setText("Maximum allowed ground coverage for building :   " + max_area + "  sq. ft.");
        }
        }
        else{
             JOptionPane.showMessageDialog(null, "please enter total land area");
           tf_total_land_area.requestFocusInWindow();
        }
    }//GEN-LAST:event_tf_max_gcoverMouseClicked

    private void tf_max_gcoverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_max_gcoverKeyPressed
        if(tf_total_land_area.getText().equals("")){
              JOptionPane.showMessageDialog(null, "please enter total land area");
           tf_total_land_area.requestFocusInWindow();
           tf_max_gcover.setText("");
       }
        
    }//GEN-LAST:event_tf_max_gcoverKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_estimate;
    private javax.swing.JComboBox<String> cb_floors;
    private javax.swing.JLabel ce_1;
    private javax.swing.JLabel ce_2;
    private javax.swing.JLabel ce_3;
    private javax.swing.JLabel ce_4;
    private javax.swing.JLabel ce_6;
    private javax.swing.JLabel ce_estimate;
    private javax.swing.JButton clear;
    private javax.swing.JComboBox<String> fromcombo;
    private javax.swing.JButton go;
    private javax.swing.JTextField input;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jarea;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField lpsw;
    public javax.swing.JTextField lun;
    private javax.swing.JTextField output;
    private javax.swing.JButton register;
    private javax.swing.JTextField tf_max_gcover;
    private javax.swing.JTextField tf_plinth_arate;
    private javax.swing.JTextField tf_total_land_area;
    private javax.swing.JComboBox<String> tocombo;
    // End of variables declaration//GEN-END:variables
}
